### ISSUE TITLE
"stack smashing detected"

### ISSUE THREAD

**Issue by ghost** [HalosGhost/enlighten#8] opened 2017-11-03 19:18 UTC
Hi!

I was about to send this for QA in Guix, when:

````
user@abyayala /gnu/store/ds0lg1c5g54mb5lxhlh9v1aiy49vssi6-enlighten-0.0.0-1.cb0bc35/bin$ ./enlighten --help
Usage: enlighten <command>
enlighten -- a very small backlight controller

Commands:
  <nothing>      get current brightness
  list           get a list of devices
  help           print this help and exit
  [+|-]<int>[%]  set brightness to int

  if + or - is specified, increment or
  decrement accordingly

  if % is specified, treat int as a
  percentage of the max brightness

set the BACKLIGHT_DEVICE environment variable
to specify a device name at runtime
*** stack smashing detected ***: ./enlighten terminated
Aborted
````

The 'list' command works, no idea if + and - work, haven't tested them.
It's an early version of the package definition.

**Comment by ghost** [comment] 2017-11-03 19:20
My user is in the 'video' group. Is there anything I could look at besides reading the code (haven't done it yet) or running it through gdb?

**Comment by HalosGhost** [comment] 2017-11-12 21:47
Thanks for opening! Sorry for the delay (was on vacation).

This happens because ``enlighten`` does incredibly naïve option parsing (it does not use ``getopt`` at the moment).

In this case, because it didn't match the case ``help`` or ``list`` but there was an argument passed, it's trying to ~~interpret ``-help`` as a number which, unsurprisingly, leads to unexpected behavior. It still prints the help message because it realizes that something has gone amiss.~~ scan ``--`` into a single-character-wide string which results in overflowing that variable's allocated space and the associated stack smashing.

This should not affect the actual setting options in any way (if you pass a sane number, it should behave sanely; and otherwise, would do the above).

The real fix for this is to detect if ``list`` was passed, detect if ``help`` was passed, detect if a sane number was passed; and do the right thing in each case. Then, if none of the cases were correct, print the help and return an error.

(It should be noted that, technically, ``enlighten`` doesn't recognize ``help`` or ``list``; it actually just recognizes the first character of the argument as being either ``h`` or ``l``. It should also be noted that I did my very best to keep the code phenomenally simple; if you haven't looked at it yet, please don't be afraid to do so.)

Consider this on my to-do list.

**Closed as completed** 2017-11-16 03:31 UTC
Labels: bug

**Comment by HalosGhost** [comment] 2017-11-16 03:38
@ng-0, this should now be solved and should never come back.

``enlighten --help`` is recognized as an error (as the help output (and the future man page) states, the correct invocation would be ``enlighten help``), but the cause of the stack smashing has been resolved, so that should not crop up again.
